project:
  type: website

website:
  title: "USAID Supply-Chaine Performance Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - dashboard.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



